ALTER TABLE chat.faq
  ADD COLUMN IF NOT EXISTS ui_category_id UUID NULL,
  ADD COLUMN IF NOT EXISTS needs_recategorization BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS published_at TIMESTAMPTZ NULL;
