package com.ctrlf.chat.faq.controller;

import com.ctrlf.chat.faq.dto.request.AutoFaqGenerateRequest;
import com.ctrlf.chat.faq.dto.request.FaqCandidateCreateRequest;
import com.ctrlf.chat.faq.dto.request.FaqCandidateExcludeRequest;
import com.ctrlf.chat.faq.dto.request.FaqDraftGenerateBatchRequest;
import com.ctrlf.chat.faq.dto.response.AutoFaqGenerateResponse;
import com.ctrlf.chat.faq.dto.response.FaqCandidateResponse;
import com.ctrlf.chat.faq.dto.response.FaqDraftCreateResponse;
import com.ctrlf.chat.faq.dto.response.FaqDraftGenerateBatchResponse;
import com.ctrlf.chat.faq.service.FaqCandidateService;
import com.ctrlf.chat.faq.service.FaqService;
import jakarta.validation.Valid;
import java.util.List;
import java.util.UUID;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

/**
 * 관리자용 FAQ 후보 관리 API
 */
@Slf4j
@RestController
@RequiredArgsConstructor
@RequestMapping("/admin/faq/candidates")
public class AdminFaqCandidateController {

    private final FaqCandidateService faqCandidateService;
    private final FaqService faqService;

    /**
     * FAQ 후보 생성
     */
    @PostMapping
    public ResponseEntity<UUID> createCandidate(@RequestBody FaqCandidateCreateRequest request) {
        UUID candidateId = faqCandidateService.create(request);
        return ResponseEntity.ok(candidateId);
    }

    /**
     * FAQ 후보 목록 조회
     *
     * @param domain 도메인 (선택)
     * @param status 상태 (NEW / ELIGIBLE / EXCLUDED)
     */
    @GetMapping
    public List<FaqCandidateResponse> getCandidates(
        @RequestParam(required = false) String domain,
        @RequestParam(required = false) String status
    ) {
        log.info("[FAQ 후보 목록 조회] 요청 수신: domain={}, status={}", domain, status);
        
        List<FaqCandidateResponse> response = faqCandidateService.getCandidates(domain, status);
        
        log.info("[FAQ 후보 목록 조회] 응답 반환: totalCount={}, items={}", 
            response.size(),
            response.stream()
                .map(r -> String.format("{id=%s, question='%s', domain=%s, status=%s}", 
                    r.getId(), 
                    r.getCanonicalQuestion() != null && r.getCanonicalQuestion().length() > 50 
                        ? r.getCanonicalQuestion().substring(0, 50) + "..." 
                        : r.getCanonicalQuestion(),
                    r.getDomain(),
                    r.getStatus()))
                .toList());
        
        return response;
    }

    /**
     * FAQ 후보 → AI 초안 생성
     */
    @PostMapping("/{candidateId}/generate")
    public FaqDraftCreateResponse generateDraft(
        @PathVariable UUID candidateId
    ) {
        UUID draftId = faqService.generateDraftFromCandidate(candidateId);
        return new FaqDraftCreateResponse(draftId);
    }

    /**
     * FAQ 초안 배치 생성 (Phase 20-AI-2)
     */
    @PostMapping("/generate/batch")
    public FaqDraftGenerateBatchResponse generateDraftBatch(
        @RequestBody FaqDraftGenerateBatchRequest request
    ) {
        return faqService.generateDraftBatch(request);
    }

    /**
     * 자동 FAQ 생성 (질문 로그 기반)
     * 
     * 사용자 질문 로그를 분석하여 자동으로 FAQ 후보를 선정하고 초안을 생성합니다.
     * 
     * @param request 자동 FAQ 생성 요청
     * @return 자동 FAQ 생성 응답
     */
    @PostMapping("/auto-generate")
    public AutoFaqGenerateResponse generateAuto(
        @RequestBody AutoFaqGenerateRequest request
    ) {
        log.info("[FAQ 자동 생성] 요청 수신: domain={}, minFrequency={}, daysBack={}, maxCandidates={}, autoGenerateDrafts={}",
            request.getDomain(), request.getMinFrequency(), request.getDaysBack(),
            request.getMaxCandidates(), request.getAutoGenerateDrafts());
        
        AutoFaqGenerateResponse response = faqService.generateAuto(request);
        
        log.info("[FAQ 자동 생성] 응답 반환: status={}, candidatesFound={}, draftsGenerated={}, draftsFailed={}, draftsCount={}, errorMessage={}",
            response.getStatus(), response.getCandidatesFound(), response.getDraftsGenerated(),
            response.getDraftsFailed(), 
            response.getDrafts() != null ? response.getDrafts().size() : 0,
            response.getErrorMessage());
        
        return response;
    }

    /**
     * FAQ 후보 반려 (제외 처리)
     * 
     * FAQ 후보를 제외 처리하여 상태를 EXCLUDED로 변경합니다.
     * 
     * @param candidateId FAQ 후보 ID
     * @param request 반려 요청 (사유 포함)
     */
    @PostMapping("/{candidateId}/reject")
    public void rejectCandidate(
        @PathVariable UUID candidateId,
        @Valid @RequestBody FaqCandidateExcludeRequest request
    ) {
        log.info("[FAQ 후보 반려] 요청 수신: candidateId={}, reason={}", candidateId, request.reason());
        
        faqCandidateService.excludeCandidate(candidateId, request.reason());
        
        log.info("[FAQ 후보 반려] 처리 완료: candidateId={}", candidateId);
    }
}
