package com.ctrlf.chat.faq.dto.request;

import lombok.Getter;
import lombok.Setter;

/**
 * 자동 FAQ 생성 요청 DTO
 * 
 * 사용자 질문 로그를 분석하여 자동으로 FAQ 후보를 선정하고 초안을 생성합니다.
 */
@Getter
@Setter
public class AutoFaqGenerateRequest {

    /** 도메인 필터 (선택, 예: SEC_POLICY, PII_PRIVACY) */
    private String domain;

    /** 최소 질문 빈도 (기본 3회) */
    private Integer minFrequency;

    /** 조회 기간 (일, 기본 30일) */
    private Integer daysBack;

    /** 최대 후보 수 (기본 20개) */
    private Integer maxCandidates;

    /** 자동으로 FAQ 초안 생성 여부 (기본 true) */
    private Boolean autoGenerateDrafts;
}

